#!/bin/sh

case "$1" in
	start)
        cmos_netserver_test &
	cmos_get_lux &
		[ $? = 0 ] && echo "OK" || echo "FAIL"

		;;
	stop)

		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
